services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"



